siemens/ngx-datatable

- projects/ngx-datatable/src/lib/components/datatable.component.html
No tabindex on the scrollable body of the datatable, therefore can't be selected (tabbed into).
And according to:
https://dequeuniversity.com/rules/axe/4.3/scrollable-region-focusable?application=axeAPI
The tabindex is expected on the scrollable part.
Can now jump into the datatable and scroll with keyboard interactions.
-
> fix: tabindex on scrollable datatable body

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
Ensures that the rows (data) are loaded correctly when the layout of the
table has changed. This applies especially to changes for resizing the
view port which let page size increase or decrease.
Page event is not fired when page size changes due to resize of the table body.
Fires page event when page size changes. Avoids display data/row gaps on table resize.
> fix: emit page event on page size change for virtual paging

- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
Before this patch, when an Angular component gets destroyed (e.g. for
recreation by parent) while a long-click is in progress, a TypeError
could be thrown.
See swimlane#1763
> fix: fix clearTimeout/_destroySubscription race

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
Empty table does not support custom content. Only possible to display the value of `emptyMessage` of type string.
Supports now custom content for an empty table within the table body. Gives the consumer the possibility to use additional components within the table. In our case, for example, a component that contains text and an icon to display empty data in a table.
> feat: support custom content for empty table

- projects/ngx-datatable/src/lib/components/datatable.component.ts
See swimlane#1470, swimlane#1975
See swimlane#1470
See swimlane#1975
> fix: don't execute sortInternalRows if externalSorting is true

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/basic/empty.component.ts
Before, the developer had to specify a flag, if the table shall use a custom empty
comonent. Now the flag is not needed any more. Makes the API cleaner. Either
a custom empty component is available or not.
BREAKING-CHANGE: remove usage of emptyCustomContent input
> refactor(custom-empty-component): use custom empty component if existent

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.html
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.scss
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.ts
- projects/ngx-datatable/src/lib/components/columns/column-ghost-cell.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/lib/themes/_ghost.scss
- projects/ngx-datatable/src/lib/themes/bootstrap.scss
- projects/ngx-datatable/src/lib/themes/material.scss
- projects/ngx-datatable/src/lib/types/table-column.type.ts
- projects/ngx-datatable/src/lib/utils/column-helper.ts
- projects/ngx-datatable/src/public-api.ts
- src/app/paging/paging-virtual.component.ts
- src/app/paging/scrolling-server.component.ts
Today, datatable with pagination on server side doesn't have ghost loaders to indicate data is being loaded.
This PR adds option to enable ghost loader which can be used to indicate data is being loaded from server while doing pagination
https://user-images.githubusercontent.com/3906709/153598878-93bf579e-2dc0-4389-bfae-9389cd22e762.mov
> fix: fix loading indicator to support ghost loader

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
Ghost cells shows up by default when data is loading
Ghost cells appear only if ghostLoadingIndicator is true
> fix(ngx-datatable): hide ghost cells based on ghosLoadingIndicator flag

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
Currently there is no a11y label for expand collapse icons
This change will add aria-label to expand collapse icons
> fix(a11y): add aria-label for datatable tree icons

- src/app/basic/disabled-rows.component.ts
The "[Source](https://github.com/siemens/ngx-datatable/blob/master/src/app/rows/disabled-rows.component.ts)" link in the ngx-datatable demo app for the [disable row](https://siemens.github.io/ngx-datatable/#disabled) functionality is broken.
Updated the link for the "Source" code for the disable row functionality to the [correct](https://github.com/siemens/ngx-datatable/blob/master/src/app/basic/disabled-rows.component.ts) link.
**Other …
> docs: fixed disabled row demo code link

- projects/ngx-datatable/src/lib/utils/math.spec.ts
- projects/ngx-datatable/src/lib/utils/math.ts
For some inputs the function scaleColumns(colsByGroup: any, maxWidth: any, totalFlexGrow: any) in utils/math.ts returns a set of column with total width exceeding that of the maxWidth argument.
This seems to be the reason for a horizontal scrollbar on large screens where space is more than enough.
After auto-caling the columns in flex mode, a correction is made based on the outstanding overflow/underflow by adding/removing the delta from the biggest column.
If this PR contains a breaking change, please describe the impact and migration path for …
> fix(scaleColumns): adjust for overflow when scaling columns in flex mode

- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/selection.component.ts
Allows user to select all rows with keyboard `meta+a` or `ctrl+a`. This only selects rows which are currently available to the datatable and will not select rows which get loaded from server in future by user actions like scrolling/paging
Currently there is no effect when user press ctrl + A or meta + A on mac.
When focus inside table on row and user presses ctrl+A or meta + A, all available rows will be selected and selection event will be emitted.
If this PR contains a breaking change, please describe the impact and migration path for existing …
> feat: support keyboard shortcuts for all rows selection

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Allows to keep external pagination components to be in sync with current page value.
**What is the current behavior?** (You can also link to an open issue here) 
external pagination component will not update the page number when user sort the columns
external pagination component's page number stays in sync with the datatable offset value.
> fix: page not emitted when columns are sorted

- projects/ngx-datatable/src/lib/utils/prefixes.ts
This is to fix an issue on Firefox 126 (released May 2024), which no longer support `-moz-transform` but `transform`. But when we get style attributes from an element, `-moz-transform` is still available, which makes our `testStyle` fails. So to resolve this issue, we want to use unprefixed attribute if available.
The issue happens if we use `virtualization`, screenshot below:
> [b] Prefer unprefixed style attribute over prefixed one

- projects/ngx-datatable/src/lib/components/body/body.component.ts
Fixes the issue where it is not possible to scroll horizontally when there is no data causing some columns headers to not be visible.
> fix(scroll): horizontal scroll is disabled with empty rows

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/utils/sort.ts
- src/app/basic/row-grouping.component.ts
Internal sorting doesn't work when row grouping feature is used with datatable.
If the sort column is used as group then groups are sorted otherwise rows within each group is sorted within that group
> fix(row-grouping): sorting with grouped rows

- docs/SUMMARY.md
- docs/api/row/row-def.md
- package-lock.json
- package.json
- projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/lib/themes/material.scss
- projects/ngx-datatable/src/public-api.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/drag-drop/drag-drop.component.ts
Introduced `DatatableRowDefComponent` which can be used by consumers to pre apply certain directives on each row.
Usage:
```html
<ngx-datatable>
<ng-template rowDef>
<datatable-row-def cdkDrag />
</ng-template>
</ngx-datatable>
```
> feat(rows): wrapper for pre applying directives

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- src/app/basic/row-grouping.component.ts
fixes the issue where `rowHeight` on `ngx-datatable-group-header` doesn't work
> fix(row-group): group header row height

- projects/ngx-datatable/src/lib/components/body/body.component.ts
fixes the issue where `collapseAllGroups` and `expandAllGroups` methods don't work in case of grouped rows with `groupExpansionDefault` set to `true`.
> fix(rows): expand collapse not working correctly

- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- src/app/sorting/sorting-default.component.ts
Introduced `enableClearingSortState` which allows to clear the sort on particular column after performing ascending and descending sort.
Similar to what angular material table provides:
https://material.angular.io/components/table/overview#table-sorting
> feat(sort): support to remove applied sort

- projects/ngx-datatable/src/lib/components/datatable.component.ts
fixes the issue where `ngDoCheck` goes into infinte loop when `disableRowCheck` is provided.
> fix(disabled-rows): recalculate only if row differs

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Fixes the issue where  tree grouping breaks if rows are directly set on ngx-datatable without doing any async calls.
> fix: tree grouping breaks if rows are assigned statically

- projects/ngx-datatable/src/lib/components/datatable.component.ts
value setter is defined on `@ContentChildren` to perform computation
invoke computation in `ngAfterContentInit` instead of setter.
> refactor: remove unnecessary getter/setters on columnTemplates

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-group-header-template.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-group-header.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/columns/column-cell.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.spec.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail-template.directive.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- projects/ngx-datatable/src/lib/types/table-column.type.ts
- projects/ngx-datatable/src/lib/utils/column-helper.ts
- src/app/basic/row-detail.component.ts
- src/app/basic/row-grouping.component.ts
> fix: type cell context

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.html
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/footer/footer.component.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- src/app/basic/row-grouping.component.ts
> refactor: switch to control flow syntax

- projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
This has following changes:
- Switched to use signal for `temp` iterator which was used for rendering the rows on view also renamed `temp` to `rowsToRender`.
- `getRowsStyles` and `bottomSummaryRowsStyles` converted to `computed` signals to avoid calling them unnecessarily. This should lead to some performance boost.
> refactor: use signals to render internal rows

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Currently on initialization internal sort is called multiple times (>4) which is not needed.
Also sort is called twice when ghost loading is enabled with virtual infinite scroll.
`sortInternalRows` is called only once avoiding redundant calls. 
> refactor: avoid duplicate sort calls

- projects/ngx-datatable/src/lib/components/body/body.component.ts
fix to avoid duplicate trackBy index warning thrown when using virtual scroll with ghost loader.
> refactor: duplicate trackBy index warnings

- projects/ngx-datatable/src/lib/components/datatable.component.ts
This one is regression of https://github.com/siemens/ngx-datatable/pull/91
Steps to reproduce:
- load table with some rows
- on some button click do rows = [] 
- console throws errors
> fix: resetting table with empty array

- projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
indexes are now signals which allows to make `rowsToRender` as `computed` depending on changes in `indexes`;
this allows to remove manual calls to `updateRows` from everywhere and ensures to be called when indexes are changed.
on a side effect it also fixes manually removing dummy ghost rows.
> refactor: use signals for indexes

- projects/ngx-datatable/src/lib/components/datatable.component.ts
This issue occurs mainly when table is hidden using `display:none`
Column widths are calculated on load even when table is not visible.
Even though recalculation is again triggered when table visibility change it leads to wrong width calculations as it calculates based on pervious widths of columns.
> fix: calculate column widths only when table is visible

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- src/app/paging/paging-scrolling-novirtualization.component.ts
1. Configure a basic `ngx-datatable` with some arbitrary data as well as a text input 
2. Define a boolean representing loading (initially false) and bind it to the `ghostLoadingIndicator` of the datatable
3. On input / search set the loading boolean to true (and optionally to false after a while)
4. Observe the behaviour of the datatable: existing rows are still visible while ghost cells are being displayed.
> fix: hide rows when ghostLoading with no virtualization

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/lib/utils/column-helper.ts
- projects/ngx-datatable/src/lib/utils/math.ts
added property for passing `defaultColumnWidth` with `INgxDatatableConfig` and also aligned `forceFillColumnWidths` to use correct `defaultColumnWidth`.
> feat: configurable defaultColumnWidth

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Before introducing strict types we allowed overriding messages and cssClasses partially.
currently applications needs to provide all default values even if they intend to override only one specific.
> fix: partial values for messages and cssClasses

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/header/header.component.ts
column pinning used  `transform: translate3d` to freeze columns on left/right. This approach was having significant performance issues as on every pixel scroll it calculated how much to translate so that frozen columns stays on view.
This PR changes the above approach and use css `position:sticky` to achieve the same behaviour eliminating need for
calculating pixels to translate. It also solves the flicker problems which were caused while doing horizontal scroll extremely   
fast along with column pinning.
To see the flicker problems
- go to https://siemens.github.io/ngx-datatable/#pinning 
- open it in safari where this problem is very much visible
- do horizontal scrolls
**What is the current behavior?** (You can also …
> refactor: use css sticky instead of transform

- projects/ngx-datatable/src/lib/components/body/body.component.ts
use rowHeightCache as signal which then can be used to compute scrollHeight
and removes multiple getter calls to calculate `scrollHeight`.
> refactor: use signals for rowHeightCache

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/utils/math.ts
horizontal scroll shouldn't appear on load if there is enough space available to render columns.
steps to reproduce:
1. go to example https://github.com/siemens/ngx-datatable/blob/master/src/app/basic/scrolling.component.ts 
2. keep only first 2 columns (Name and Gender) and remove rest of the columns
3. observe that horizontal scroll is still present even though 2 columns are possible to fit in view port.
> fix: horizontal scroll

- src/app/basic/contextmenu.component.ts
- src/app/basic/footer.component.ts
- src/app/basic/inline.component.ts
- src/app/basic/scrolling-dynamically.component.ts
- src/app/basic/tabs.component.ts
- src/app/columns/column-toggle.component.ts
- src/app/selection/selection-chkbox-template.component.ts
- src/app/selection/selection-chkbox.component.ts
- src/app/selection/selection-disabled.component.ts
- src/app/selection/selection-multi-click-chkbox.component.ts
- src/app/selection/selection-multi-click.component.ts
- src/app/selection/selection-multi.component.ts
- src/app/selection/selection-single.component.ts
- src/app/summary/summary-row-custom-template.component.ts
- src/app/summary/summary-row-inline-html.component.ts
- src/app/templates/template-obj.component.ts
- src/app/tree/fullscreen.component.ts
> chore: use control flow syntax for examples

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/table-column.type.ts
Removes useless annotations to reduce warnings and prepare for future TSDoc setup
> refactor: clean up TSDoc

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
Steps:
- go to row-grouping example
- select all the rows from a specific group 
- checkbox in the group state changes to checked
- now un select one of the row from the group
- checkbox in the group remains checked even though all rows under that groups are not selected
> fix: update group checkbox state on child row selection state change

- .gitattributes
- .github/workflows/test_and_deploy.yml
- .gitignore
- .lfsconfig
- e2e-local.sh
- package-lock.json
- package.json
- playwright.config.ts
- playwright/e2e/filter.spec.ts
- playwright/e2e/row-group.spec.ts
- playwright/reporters/playwright-axe-reporter.ts
- playwright/snapshots/e2e/filter.spec.ts-snapshots/filter--empty-chromium-linux.png
- playwright/snapshots/e2e/filter.spec.ts-snapshots/filter--filtered-chromium-linux.png
- playwright/snapshots/e2e/filter.spec.ts-snapshots/filter--next-page-chromium-linux.png
- playwright/snapshots/e2e/filter.spec.ts-snapshots/filter-chromium-linux.png
- playwright/snapshots/e2e/row-group.spec.ts-snapshots/row-grouping--default-chromium-linux.png
- playwright/snapshots/e2e/row-group.spec.ts-snapshots/row-grouping--group-collapsed-chromium-linux.png
- playwright/snapshots/e2e/row-group.spec.ts-snapshots/row-grouping--group-expanded-chromium-linux.png
- playwright/snapshots/e2e/row-group.spec.ts-snapshots/row-grouping--group-selected-chromium-linux.png
- playwright/support/test-helpers.ts
- playwright/support/vrt-styles.css
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- src/app/app-routing.module.ts
- src/app/basic/row-grouping.component.ts
- src/assets/app.css
- src/index.html
> ci: setup playwright

- .github/workflows/test_and_deploy.yml
- playwright.config.ts
CI runs html report server if e2e fails and creates an a11y report that is not used.
CI uses github reporter and do not run an http server or generates an unused unit report.
> ci: split e2e into separate job

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/footer/footer.component.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
Although the type says diffrently one always needed to set every CSS class.
Now one can only override partial CSS classes and the other defaults will be kept.
This is part of a larger refactoring to enable strictNullChecks
> fix: allow partial overrides of CSS classes

- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/public-api.ts
BREAKING CHANGE: Removed several symbols from the public API that were intended to be internal.
Exports everything.
Only export symbols that are meant to be used outside.
> refactor: only export symbols that are meant to be exported

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/selection.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
We sometimes declare an event around our `ActivationEvent` as `MouseEvent | KeyboardEvent` which is wrong in that case 
as a row may also gets activated by a checkbox change which Emits a normal `Event`.
Just declare everything as `Event` and add necessary type casts.
Public API is affected, but only the a new type which is not typed in the latest release anyway. So refactoring scope is correct here.
> refactor: always use type event

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
This never made any sense. `ghostLoaderTemplate` was never defined and the manual cleanup of `cellTemplate` was never really needed.
Useless cleanup code.
No useless cleanup code.
> refactor: remove useless cleanup

- playwright/e2e/row-disabled.spec.ts
- playwright/snapshots/e2e/row-disabled.spec.ts-snapshots/disabled-chromium-linux.png
- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- src/app/basic/disabled-rows.component.ts
Previously, `disableRowCheck` was called on groups instead of rows inside a group.
But we  documented that this check is called on rows.
This was leading to the problem, that it was only possible to disable entire groups instead of single rows
within in a group.
Beside this, we had an observable in some template contexts, which is a very uncommon approach.
`disableRowCheck` is only called on rows even if the rows are grouped.
The template context now only provide a normal boolean property instead of a subject.
If this PR contains a breaking change, …
> fix: only run disabled check on rows

- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/types/table-column.type.ts
Comparator function is typed as any.
Comparator function is type as expected. See sort.ts for usage.
> fix: add missing type to comparator

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/selection.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- src/app/selection/selection-cell.component.ts
- src/app/selection/selection-chkbox-template.component.ts
- src/app/selection/selection-chkbox.component.ts
- src/app/selection/selection-disabled.component.ts
- src/app/selection/selection-multi-click-chkbox.component.ts
- src/app/selection/selection-multi-click.component.ts
- src/app/selection/selection-multi.component.ts
- src/app/selection/selection-single.component.ts
The `select` event does not have its own reusable type.
The `select` event has its own reusable type which can be used in code when creating handler.
> refactor: add dedicated type for `SelectEvent`

- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
This is a refactoring as we never released typing yet.
According to our current signature rowClass is also called with groups, but it never is.
Changed the signature so rowClass is also by type never called with groups.
This MR is labeled as `refactor` since we did not release this type.
> refactor: adjust the type of rowClass as it is never called with groups

- projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- src/app/basic/responsive.component.ts
- src/app/basic/row-detail.component.ts
The details event has an anonymous type which is hard to use as it does not express the relation between the `type` field and the value.
The new type can be reused in event listener and is a discriminated union so auto TS type calculation works.
> feat: add type for details toggle event

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
- projects/ngx-datatable/src/lib/types/internal.types.ts
We previously had two event types for reordering, that had a completely different naming.
Those events are now consolidated into one following the existing naming pattern of the public API.
> refactor: always use the same event type for reorder columns

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
- projects/ngx-datatable/src/lib/types/internal.types.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
When using groups, all rows are marked as `odd`.
When using groups, all rows are marked as `even` / `odd` toggling in their group. So, the first element in a group will always be `even`.
If this PR contains a breaking change, please describe the impact and migration path for existing applications: 
Previously `CellContext.rowIndex` was a `string` if the row was inside a group. Now `CellContext.rowIndex` is always a number, either containing the index of the row or if the row is inside a group, the index of the group.
To access the index value of a row …
> fix: apply even/odd classes correctly when rows are grouped

- projects/ngx-datatable/src/lib/types/public.types.ts
- src/app/paging/paging-virtual.component.ts
We currently emit the `limit` value in the page change event.
We no longer emit the `limit` value.
Applications should use `pageSize` as this contains the actual used `pageSize`.
If they for some reason need the `limit`,  then they need to use the value they provided, as we never modify the `limit` value.
> refactor: remove limit from page event

- projects/ngx-datatable/src/lib/components/datatable.component.ts
The column resize handler is written in a weird way as `Array.map` has a side effect.
The column resize handler is written less weird and is strict `null` compatible.
Add one point we should figure out why columns are cloned, but this is up for later.
> refactor: make column resize handling typesafe

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.scss
- projects/ngx-datatable/src/lib/components/body/body-row.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/header/header.component.scss
- projects/ngx-datatable/src/lib/components/shared.scss
Various styles are located on root component level.
Styles are now located on the component level using a shared mixin.
I guess in the long run, we should consider having some shared styles that have to be imported into the global style sheet of the application to avoid duplication at runtime. With the mixin we at least do not have the code duplicated.
> refactor: move some shared styles to respective components

- projects/ngx-datatable/src/lib/components/body/body-group-header-template.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-group-header.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
- projects/ngx-datatable/src/lib/components/body/progress-bar.component.ts
- projects/ngx-datatable/src/lib/components/body/scroller.component.ts
- projects/ngx-datatable/src/lib/components/body/selection.component.ts
- projects/ngx-datatable/src/lib/components/columns/column-cell.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column-ghost-cell.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column-header.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/columns/tree.directive.ts
- projects/ngx-datatable/src/lib/components/footer/footer-template.directive.ts
- projects/ngx-datatable/src/lib/components/footer/footer.directive.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail-template.directive.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
- projects/ngx-datatable/src/lib/directives/disable-row.directive.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.ts
- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
- projects/ngx-datatable/src/lib/directives/visibility.directive.ts
The angular subproject contained explicit `standalone: true`, which is the new default and no longer required.
There are no longer any explicit `standalone: true`.
> refactor: remove explicit standalone flags

- projects/ngx-datatable/src/lib/components/body/body-row.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/header/header.component.scss
Styles around display are on the root component. Additionally, `align-items: center` and `flex-flow: row` are the defaults so setting those value is unnecessary.
Styles in the respective component and useless assignments are dropped.
`.datatable-row-center` is always a `.datatable-row-group` so styles could be simplified. Same applies for  `> div` selector in the  body-row-component.
> refactor: move display related styles to respective components

- projects/ngx-datatable/src/lib/components/header/header-cell.component.scss
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.spec.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.ts
- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
- projects/ngx-datatable/src/lib/types/internal.types.ts
- projects/ngx-datatable/src/lib/utils/events.ts
* Enabled touch event handling in key directives such as draggable, resizeable, and long-press, ensuring compatibility with touch devices.
* Introduced utility functions for identifying touch events and extracting event coordinates.
* Updated styles to enhance usability on touch devices.
Columns can't be resized or reordered.
Columns can be resized and reordered.
> feat: add touch support for reorderable and resizable features

- docs/api/table/inputs.md
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.spec.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- src/main.ts
This adds localisation for a11y labels (used on the pager).
#229 
The aria labels are hard coded and in english.
The aria labels can be optionally configured via the already existing "messages" object / input.
There are additional "messages" properties, that must be specified when using a global config.
> feat!: add localisation for a11y labels

- projects/ngx-datatable/src/lib/components/datatable.component.ts
In #192 we introduced `rows` that are always defined internally. As other setters may use `rows` before initialization (via input), a default value is required.
The property `rows` has no default value. Since the table is making use of setters to update computed values, it may be accessed before initialisation.
The property `rows` can be accessed by other setters and internal logic, even before initialisation.
See …
> fix: introduce a default value for rows

- playwright/snapshots/e2e/resize.spec.ts-snapshots/pinning--pinning-name-and-state-column-chromium-linux.png
- projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.scss
Currently we are calculating the offset for each row individually as each row is positioned absolute.
All rows are now wrapped in another container, for which the offset is calculated. No absolute positioning needed.
Why did this affect screenshots? Previously the datatable-selection has had a 'random' height as all children were absolute.
This height was somehow always appended at the bottom causing a gap between …
> perf: only calculate render offset once for all rows

- projects/ngx-datatable/src/lib/components/body/body-group-header.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
- projects/ngx-datatable/src/lib/types/internal.types.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- projects/ngx-datatable/src/lib/types/table-column.type.ts
Sometimes declarations of the generic type `TRow` has no type constraint although in fact the table generally has one. So far the constrain was only added when needed.
Declarations of `TRow` now always have a constraint.
This is mainly for consitantancy but it seems like it is also needed in certain cases for strict null checks.
> refactor: add missing Row type for TRow

- projects/ngx-datatable/src/lib/utils/sort.ts
Since ES2019 Array.sort is guaranteed to be stable.
Useless code to make output of sorting stable. (No longer needed since ES2019, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#sort_stability)
Dropped useless code for making sort output stable.
> refactor: drop useless stable sort code

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/types/internal.types.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
The `ActivationEvent` type is used in two difference context:
- on a higher level, always including the activated row HTML element
- on a lower level, not including the HTML element
The type is split into the two individual ones:
- `ActivationEvent` now enforcing a `rowElement` being defined
- `CellActivationEvent` (internal) never having a `rowElement` defined
This whole activation thing is a huge mess, based on …
> refactor: split activation event

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
The page event is currently used for two main use cases:
- custom pagination
- server side paging
Currently this event does not contain the `sorts` object for server side paging, hence consumers always must listen to sort changes as well.
This turned into a problem with #45+. Since the sort and page events are always emitted together on sort change as it may reset the page to 0.  So when implementing server side paging one has to merge the two events in case of sorting to prevent duplicate backend calls.
The page event now also contains  the `sorts` object. With this change, apps can now always use the page event and …
> feat: include sorts in page event

- .lfsconfig
The Git LFS target points to the https://github.com/siemens-research/ngx-datatable-snapshots project.
The Git LFS target points to the https://github.com/siemens/ngx-datatable-snapshots project.
The previous Git LFS issues were resolved by the GitHub support team and the old project is usable again. All files were synced manually.
> chore(lfs): swtich LFS target from `siemens-research` to `siemens`

- projects/ngx-datatable/src/lib/components/body/body.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/footer/footer.component.spec.ts
- projects/ngx-datatable/src/lib/components/footer/footer.component.ts
Hidden styling is integrated into the root style and used in multiple components.
Hidden styling is moved to body, where we keep it using to avoid recreation of elements while loading.
In the footer it is replaced by `@if`.
Brings us closer to the overall goal to enable view encapsulation.
> refactor: move or replace `[hidden]` style to drop in from global styles

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.config.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/public-api.ts
- src/main.ts
- config is provided using the string `configuration` (Angular types do not even allow injecting a string)
- there is no provider function for a standalone way
- messages and css classes are  all required when globally provided (although this is no needed)
- proper injection token is used (but `configuration` still works)
- new function to provide config in a standalone manner
- messages and css classes are all optional too and global provider
If this PR contains a breaking change, please describe the impact and migration path for existing …
> feat: introduce a new `providedNgxDatatableConfig`

- projects/ngx-datatable/src/lib/components/header/header.component.scss
- projects/ngx-datatable/src/lib/components/header/header.component.ts
We accidentally removed the flex container on column groups for pinning. Please note that we have the same in body rows where we kept the container as flex.
We were missing `display: flex` on column groups in the header. This was accidentally removed. Body rows are still having this.
Column groups in the header are now also flex container again.
This is labelled as refactoring since we never released the previous …
> refactor: all header pinned columns should be flex

- projects/ngx-datatable/src/lib/directives/disable-row.directive.ts
`DisableRowDirective` uses @Input and Setter / Getter
`DisableRowDirective` uses input signal and effects
This pull request refactors the `DisableRowDirective` to improve readability, simplify the code, and leverage Angular's reactive primitives for better state management. Changes include replacing manual state handling with the reactive `input` API, introducing the `effect` API for automatic reactivity, and …
> refactor(disable-row): migrate to input signals

- playwright/e2e/row-group.spec.ts
- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.config.ts
> fix: checkbox accessibility

- projects/ngx-datatable/src/lib/utils/math.spec.ts
- projects/ngx-datatable/src/lib/utils/math.ts
In flex mode, resizing is broken. The problem is that when calculating the new sizes after resizing, the original `maxWidth ` is subtracted by the width of columns that cannot be rescaled (typically the column that was resized).
But in the end it is checked whether the sum of ALL columns matches the `maxWidth` to compensate rounding errors.
Yet this never happens, as the non rescalable are missing so the table over compensates.
The original `maxWidth` is not modified so the table no longer overcompensates.
If this PR contains a breaking change, please …
> fix: calculate correct column width in flex mode after resize

- playwright/e2e/selection.spec.ts
- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
There is unused code for sorting in the body-cell.
The body-cell cannot sort and does not know about sorting so this code was useless and actually also unused,
as the input triggering was never called.
The only notable consumer change is, that body-cells no longer have the class `sort-active`. But I guess this is fine.
> refactor: drop unused code in body-cell

- CODEOWNERS
The `CODEOWNERS` file was mentioning individual users.
The `CODEOWNERS` file is using GitHub teams to directly derive the intended code owners.
> ci(codeowners): switch from single users to GitHub teams

- eslint.config.mjs
- projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- projects/ngx-datatable/src/lib/utils/table-token.ts
- src/app/basic/disabled-rows.component.ts
- src/app/sorting/sorting-client.component.ts
- src/app/sorting/sorting-server.component.ts
Internal member with _ prefix which were public before are now marked as private or protected.
These members were never meant to be public.
> refactor: enable naming-convention rule

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/utils/number-or-undefined-attribute.ts
When passing a limit, it is always transformed by the `numberAttribute` converter. This always converts `undefined` to `NaN` which breaks the table.
With this change, we use a modified version that passes undefined through.
Closes #349
> fix: no error on undefined limit

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/footer/footer.component.spec.ts
- projects/ngx-datatable/src/lib/components/footer/footer.component.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.spec.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/footer/testing/pager.harness.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/public-api.ts
- src/app/basic/footer.component.ts
When building a custom footer, our pagination is no longer included, but typically still required. With previous versions, apps could re-use our internal pager, as everything was exported. This was stopped for good reasons.
This commit now adjusts the pager to being exported again. Now the pager automatically picks the table state, leading to the removal of all input/outputs. The selector is also changed to `ngx-datatable-pager` to match the pattern of the already exported components.
If this PR contains a breaking change, please describe the impact …
> feat: export pager component for reuse in custom footer

- package-lock.json
- package.json
The `cross-env` dependency was part of the `package.json`, but no longer used (see https://github.com/search?q=repo%3Asiemens%2Fngx-datatable%20cross-env&type=code), causing pointless version bumps: https://github.com/siemens/ngx-datatable/pull/369.
The unused `cross-env` dependency is no longer part of the `package.json`.
> chore(deps): drop cross-env dependency since no longer used

- tools/semantic-release/writer-opts.js
Commits with hidden types with notes were not showing their scope. 
> The term notes in the context of semantic release means all options like NOTE:, DEPRECATED: or BREAKING CHANGE:.
Commits with hidden types that include notes now display their scope when a changelog is generated with semantic release.
**Other information**:  Same as https://github.com/siemens/element/pull/526
> build(semantic-release): fix scope for hidden commit types with notes

- projects/ngx-datatable/src/lib/utils/sort.ts
console throws errors and sort doesn't work when doing sort on column which is also used as a grouped row key
steps to reproduce:
- go to https://siemens.github.io/ngx-datatable/#/row-grouping
- click on age column to sort
- see console
> fix(sort): sort on grouped header column throws errors

- package-lock.json
- package.json
E2E dependencies are listed as optional dependency.
E2E dependencies are listed as dev dependency.
Having them as optional dependency was never used. They were also always installed on every CI build.
So just moving them dev dependencies. Also aligns it with element where we are no longer having them as optional.
> build: move e2e packages to dev dependencies
