siemens/ngx-datatable

- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
Original PR: swimlane#2005
Fix CSP issue: swimlane#1560
swimlane#1560
Original PR: swimlane#2005
> fix: fix CSP script-src 'self'

- projects/ngx-datatable/src/lib/components/body/body.component.ts
See swimlane#1798, swimlane#1830
See swimlane#1798, swimlane#1830
> fix: refresh virtual grid after scroll

- src/app/paging/paging-virtual.component.ts
caching in demo ignores page size - this depends on how many rows are visible
throw away the cache when the page size changes
> chore(demo): fix cache in paging-virtual example

- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
See swimlane#1814
See swimlane#1814
See swimlane#1814
> fix: fix orderable directive

- projects/ngx-datatable/src/lib/components/body/body.component.ts
https://code.siemens.com/simpl/simpl-element/-/issues/401
User will not have to explicitly move scrollbar to see blank rows updated after doing scroll 
> fix: redraw issue with virtual scroll while dragging scrollbar 

- package-lock.json
- package.json
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/scroller.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/themes/material.scss
- src/app/app.component.html
- src/app/app.module.ts
- src/app/basic/scrolling-dynamically.component.ts
**What is the current behavior?** The component doesn't support dynamic vertical scrolling.
**What is the new behavior?** There is an opt-in mode to support dynamic vertical scrolling.
> feat: enable vertical scrolling on demand

- projects/ngx-datatable/package.json
The library can not be installed on projects using rxjs 7 (ie Angular 13)
The library can be installed on projects using rxjs 7 (ie Angular 13)
> chore: add support for rxjs ^7.4.0

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/selection.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/directives/disable-row.directive.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
- projects/ngx-datatable/src/lib/themes/_rows.scss
- projects/ngx-datatable/src/lib/themes/bootstrap.scss
- projects/ngx-datatable/src/lib/themes/material.scss
- projects/ngx-datatable/src/public-api.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/basic/disabled-rows.component.ts
Today there is no direct way to mark datatable row as disabled
This PR will provide option to make row disable 
https://code.siemens.com/simpl/simpl-element/-/issues/630
> Feat(ngx datatable)/provide support to disable row

- angular.json
**What is the current behavior?** The build fails due to build budget voilation.
**What is the new behavior?** The build succeeds. 
> fix: increase style file budget to meet material theme file

- projects/ngx-datatable/src/lib/components/body/body.component.ts
> fix: remove empty placeholder rows after actual data is rendered

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Throws console error when rows set to undefined and ghostLoading is enabled
Removes console error.
> fix: console error with ghostLoadingIndicator

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/drag-events.type.ts
- src/app/paging/paging-client.component.ts
> feat(datatable): allow row drag and drop

- projects/ngx-datatable/src/lib/components/body/body.component.ts
**What is the current behavior?** The HTML `dragleave` event is not exposed on row level.
**What is the new behavior?** One can subscribe to all HTML `dragleave` row level events.
> fix: emit drag leave event

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
> fix(disable-row): allow disabling through side effects without mutating rows

- docs/changelog.md
The numbers in parentheses are currently greater than the newest PR/issue and thus don't make sense. Eventually there will be enough PRs/issues such that the numbers will be incompatible and confusing.
References are clearly to the other repository
> docs: link to swimlane/ngx-datatable

- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
User cannot use keyboard to apply sorting on table header cells
Allows to tab through header cells and apply sorting
> fix(header): support tabbing over header cells

- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- src/app/basic/row-grouping.component.ts
Not possible to select rows if row grouping feature is used.
Allows to use row selection feature along with row grouping.
> fix(row-grouping): row selection with grouped rows

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
fixes endless horizontal scroll behaviour when using grouped rows.
> fix(scroll): horizontal scroll with grouped rows

- projects/ngx-datatable/src/lib/components/body/body.component.ts
regression of https://github.com/siemens/ngx-datatable/pull/57
> fix(empty-data): use correct width for empty data

- projects/ngx-datatable/src/lib/components/datatable.component.ts
> ci: fix unit test

- projects/ngx-datatable/src/lib/components/header/header.component.ts
fixes lint errors
- [] Refactoring (no functional changes, no api changes)
> chore: fix lint errors

- .github/workflows/test_and_deploy.yml
> chore: run actions on pull_request

- projects/ngx-datatable/src/lib/components/body/body-group-header.directive.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/themes/material.scss
- src/app/basic/row-grouping.component.ts
Provide option to show checkbox on group header rows for selection of rows within particular group.
> feat(row-group): row group with checkbox

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/utils/table-token.ts
> fix: cyclic import

- .github/workflows/test_and_deploy.yml
- package-lock.json
- package.json
Library prod build was not run in actions.
Now, added prod build of library and packaging.
> ci: include library prod build in ci

- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
> refactor: use unique keys for trackBy

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/scroller.component.ts
- projects/ngx-datatable/src/lib/components/columns/column-cell.directive.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/columns/tree.directive.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
- projects/ngx-datatable/src/lib/directives/disable-row.directive.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.ts
- projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
- projects/ngx-datatable/src/lib/directives/resizeable.directive.ts
- projects/ngx-datatable/src/lib/directives/visibility.directive.ts
- projects/ngx-datatable/src/lib/services/scrollbar-helper.service.ts
Switch to `inject` syntax instead of using constructor style DI 
> refactor: use inject api instead of constructor for DI

- projects/ngx-datatable/src/lib/components/body/body.component.ts
only update rowExpansions in case of using row details.
> refactor: avoid unnecessary loops

- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/types/table-column.type.ts
> fix: add missing type for header and cell style classes

- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/footer/footer.directive.ts
- projects/ngx-datatable/src/lib/directives/disable-row.directive.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.ts
- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
- projects/ngx-datatable/src/lib/directives/resizeable.directive.ts
> refactor: use built in transform for boolean and number inputs

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
use angular's built in feature to fallback to default content in case of no custom projection.
> refactor: use fallback content projection

- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/basic/filter.component.ts
- src/app/basic/scrolling-dynamically.component.ts
- src/assets/app.css
Using ng-if to mimic a router.
Using a router.
> docs: use router instead of ng-if

- angular.json
- tsconfig.json
> build: switch to esbuild

- .github/workflows/test_and_deploy.yml
> ci: upload e2e results artifacts

- CODEOWNERS
We don't have codeowners
We have codeowners
> docs: add a code owner file

- projects/ngx-datatable/src/lib/components/body/body.component.ts
Unused import. 
No unused import
> refactor: remove unused import

- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/ngx-datatable.module.ts
Messages cannot be overridden partially.
Messages can be overridden partially.
This is part of a larger refactoring to enable strictNullChecks
> fix: allow partial overrides of messages

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/utils/column-helper.ts
"Converting" (a very weird way of copy) column directives to normal column objects was written in a weird complex way.
Just normal cloning the column of columns
This is part of a larger refactoring to enable stricter compiler checks.
> refactor: simplify column directive converting

- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
Unused loop index.
No unused loop index.
> refactor: remove unused loop index

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/directives/draggable.directive.ts
- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
- projects/ngx-datatable/src/lib/directives/resizeable.directive.ts
- projects/ngx-datatable/src/lib/utils/column-prop-getters.ts
- src/app/basic/disabled-rows.component.ts
- tsconfig.json
Strict function type is not enabled.
Strict function type is enabled and some issues are fixed related to this.
> refactor: enable `strictFunctionTypes`

- src/app/sorting/sorting-server.component.ts
Our sort event is not well typed, so we need a workaround in example codes.
Added workaround.
> docs: add missing type for sorting

- src/app/paging/paging-scrolling-novirtualization.component.ts
- src/app/paging/paging-server.component.ts
- src/app/summary/summary-row-server-paging.component.ts
The example conflicts with strictNull checks and has implicit any as function params are untyped.
Methods are more simple and properly typed.
Using page instead of offset is weird. But I guess we can fix this in another MR.
> docs: add missing type for server paging

- src/app/basic/css.component.ts
This example has an untyped function for cell classes.
This function is now typed.
> docs: fix typing of cell class

- projects/ngx-datatable/src/lib/utils/math.ts
Type unsafe iteration over column in groups.
Type safe iteration over column in groups.
> refactor: simplify column in group iteration

- projects/ngx-datatable/src/lib/directives/orderable.directive.ts
- projects/ngx-datatable/src/lib/utils/math.ts
- projects/ngx-datatable/src/lib/utils/sort.ts
- projects/ngx-datatable/src/lib/utils/tree.ts
Some local types in functions are missing.
No local types in functions are missing.
> refactor: add missing internal types

- projects/ngx-datatable/src/lib/components/body/body.component.ts
The template has type errors which are not suppressed.
Type errors are suppressed.
I will fix those later in a proper way. But for now the goal is to enalbe strict: true in the tsconfig.
> refactor: disable type check around detail height

- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/types/public.types.ts
- src/app/basic/contextmenu.component.ts
The context menu event had an anonymous type.
The context menu event has a reusable type that uses a discriminated union to allow better usage.
> feat: add type for context menu event

- projects/ngx-datatable/src/lib/utils/column.ts
- projects/ngx-datatable/src/lib/utils/math.ts
Having two functions which basically do the same with a param that is never passed.
One function only having parameters that are used.
> refactor: simplify total width calculation

- src/app/basic/css.component.ts
- src/app/basic/dynamic-height.component.ts
- src/app/basic/filter.component.ts
- src/app/basic/responsive.component.ts
- src/app/basic/row-detail.component.ts
- src/app/basic/virtual.component.ts
- src/app/drag-drop/drag-drop.component.ts
- src/app/selection/selection-cell.component.ts
- src/app/selection/selection-chkbox-template.component.ts
- src/app/selection/selection-chkbox.component.ts
- src/app/selection/selection-disabled.component.ts
- src/app/selection/selection-multi-click-chkbox.component.ts
- src/app/selection/selection-multi-click.component.ts
- src/app/selection/selection-multi.component.ts
- src/app/selection/selection-single.component.ts
- src/app/sorting/sorting-comparator.component.ts
- src/app/sorting/sorting-server.component.ts
- src/app/summary/summary-row-server-paging.component.ts
Many example functions are lacking typed parameters.
Many example functions are no longer lacking typed parameters.
> docs: add missing type for functions

- src/app/basic/disabled-rows.component.ts
- src/app/basic/inline.component.ts
- src/app/basic/live.component.ts
- src/app/basic/row-grouping.component.ts
- src/app/basic/scrolling-dynamically.component.ts
- src/app/data.model.ts
Update value functions / and checkGroups were lacking types.
Types are added.
> docs: add missing type for updateValue functions

- projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
- projects/ngx-datatable/src/lib/test/jasmine-matchers.ts
- projects/ngx-datatable/src/lib/utils/math.spec.ts
- tsconfig.json
No TypeScript `implicitAny` enabled.
TypeScript `implicitAny` is enabled.
> build: enable noImplicitAny in tsconfig

- projects/ngx-datatable/src/lib/directives/long-press.directive.ts
This PR removes dead/useless code in the long-press directive:
1. The `longPressing` event was not used at all so it can be removed.
2. The `onMouseMove` method is pointless, as it will only be called if `isLongPressing=true` but in that case it does not do anything.
Removed the dead/useless code.
> refactor: remove unused code in long-press directive

- projects/ngx-datatable/src/lib/utils/throttle.ts
Implicit this in throttle decorator.
No implicit this in throttle decorator.
> refactor: remove implicit this in the throttle decorator

- projects/ngx-datatable/src/lib/utils/tree.ts
There is an implicit `this` call in the tree utils. Besides this, many types were missing.
The implicit `this` call is removed and missing types are added.
> refactor: remove implicit this from tree grouping

- projects/ngx-datatable/src/lib/components/datatable.component.ts
Looking up the value twice in the map.
Only look up the value once. 
Prepares for strict null checks.
> refactor: avoid redundant value lookup in map

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/scroller.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
There are many errors around strict null checks in the code.
There are still many errors around strict null checks in the code but a little less.
The changes where chosen because they were easy to do. There is no general relation between those changes except that they serve to reduce the amount of strict null errors.
> refactor: add undefined to types were needed

- src/app/app-routing.module.ts
- src/main.ts
No Lazy load component within the examples.
Lazy load components within the examples. Initial load time should be faster.
It was just bothering me. As mentioned slight improvement of the initial loading time.
> docs: lazy load examples

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.scss
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.scss
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.scss
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.scss
The body component styles are on root component level.
The body component styles are in the respective component.
> refactor: move body styles to component level

- playwright/e2e/tree.spec.ts
- playwright/snapshots/e2e/tree.spec.ts-snapshots/client-tree--client-tree-chromium-linux.png
- playwright/snapshots/e2e/tree.spec.ts-snapshots/fullscreen-tree--fullscreen-tree-chromium-linux.png
- projects/ngx-datatable/src/lib/utils/tree.ts
The tree construction is written in a complex way and is currently broken because a bug was recently added.
The tree construction is less complex and the bug is gone.
The bug was never released, so no fix commit.
> refactor: simplify tree construction

- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/header/header-cell.component.scss
- projects/ngx-datatable/src/lib/components/header/header.component.scss
The header style is located on root component level.
The header style is located on the component level.
> refactor: move fixed-header styles to component level

- projects/ngx-datatable/src/lib/components/body/body-row-def.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.directive.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
> refactor: remove duplicate template code

- projects/ngx-datatable/src/lib/components/body/body.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
The horizontal scroll style is located on root component level.
The horizontal scroll style is located on the component level.
> refactor: move horizontal scroll styles to respective components

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- src/app/paging/paging-virtual.component.ts
Internal rows can be `null`/`undefined` which is treated the same way as an empty array.
Internal rows are guaranteed to be defined.
This prepares strict `null` checks.
> refactor: ensure that rows are always defined internally

- playwright/snapshots/e2e/tree.spec.ts-snapshots/client-tree--client-tree-chromium-linux.png
- playwright/snapshots/e2e/tree.spec.ts-snapshots/fullscreen-tree--fullscreen-tree-chromium-linux.png
- projects/ngx-datatable/src/lib/utils/tree.ts
> chore: tree level should start from 0

- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/themes/material.scss
Unused CSS style definitions.
Less unused CSS style definitions.
> refactor: remove unused styles

- projects/ngx-datatable/src/lib/components/body/body-cell.component.scss
- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.scss
- projects/ngx-datatable/src/lib/components/body/body.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
The fixed-row style is located on root component level.
The fixed-row style is located on the component level.
> refactor: move fixed-row styles to respective components

- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/header/header.component.ts
> refactor: don't render wrapper if col group columns are empty

- .github/workflows/test_and_deploy.yml
Unnecessary checkout of Git LFS for unit tests.
No unnecessary checkout of Git LFS for unit tests.
> build: only fetch snapshots if needed

- projects/ngx-datatable/src/lib/components/body/body.component.ts
Lots of incorrect types.
Fewer incorrect types.
This is fixing an issue reported when strict null checks are enabled.
> refactor: add missing null and declaration

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
The `rowWrapper` has two different fields for the template context. But they are never used in paralell.
The two fields are merged into one. 
This is needed for strict null checks. As there is always one context available, merging them allows to define it as always defined.
> refactor: merge contexts into one object to avoid type issues

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
The `rowWrapper` has a group signal, which only holds a value, if the row is a group..
The row is used directly with proper checks.
Two reasons to change this:
- A potential bug: Row is not a signal, so a group would never get updated if a row changed.
- Needed for strict null checks.
> refactor: drop useless group signal

- docs/api/table/outputs.md
- projects/ngx-datatable/src/lib/components/body/body.component.ts
There is an unused internal event.
There is one unused internal event less.
> refactor: remove unused internal event

- projects/ngx-datatable/src/lib/components/body/body-cell.component.scss
- projects/ngx-datatable/src/lib/components/datatable.component.scss
- projects/ngx-datatable/src/lib/components/header/header-cell.component.scss
- projects/ngx-datatable/src/lib/components/shared.scss
Cell styles are in a global unscoped stylesheet.
Cell styles are in there respective components.
Preparation for unit testing to have all required styles in the respective components.
> refactor: move cell styles into respective components

- playwright/e2e/paging.spec.ts
- src/app/paging/mock-server-results-service.ts
In our e2e test we wait for the ghost loader to disappear as we approx 1.5 s fake loading time.
This is causing issues in CI when the loading is too short and also slows down the test.
Fixed 1 ms loading time. This still requires the app layout changes but is too fast to be noticed by e2e.
So tests are faster and less flaky.
Flakiness was not a real issue in pipelines but a problem running locally with trace.
> test: decrease fake loading time

- projects/ngx-datatable/src/lib/components/body/body.component.ts
Arrow keys don't work when cell is selected
Works again
> fix: fix keyboard interaction for cell selection mode

- .github/workflows/release.yml
- .github/workflows/test_and_deploy.yml
- .prettierignore
- .releaserc.js
- package-lock.json
- package.json
- projects/ngx-datatable/package.json
- tools/semantic-release/config.js
- tools/semantic-release/writer-opts.js
- Releases are done manually on a local computer.
- Changelog is in docs folder.
- A release is run in a pipeline.
- Changelog is in /CHANGELOG.MD.
Similar setup as in https://github.com/siemens/element:
- always requires a manual trigger
- normal release on main branch
- maintenance releases from maintenance branches
- pre-release does not really work
> build: use semantic-release instead of manual release flow

- playwright/snapshots/e2e/tree.spec.ts-snapshots/fullscreen-tree--fullscreen-tree-chromium-linux.png
- projects/ngx-datatable/src/lib/utils/column-helper.ts
The custom tree template was not working
Custom tree template should work as expected
> fix: tree custom template issue not working

- eslint.config.mjs
- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-group-header.directive.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/columns/column.directive.ts
- projects/ngx-datatable/src/lib/components/footer/footer.directive.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
- projects/ngx-datatable/src/lib/utils/math.ts
> refactor: enable prefer-nullish-coalescing

- eslint.config.mjs
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.ts
- src/app/basic/responsive.component.ts
- src/app/columns/column-reorder.component.ts
- src/app/paging/paging-virtual.component.ts
- src/app/paging/scrolling-server.component.ts
- src/app/summary/summary-row-custom-template.component.ts
- src/app/summary/summary-row-simple.component.ts
> refactor: enable consistent-component-styles

- eslint.config.mjs
- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.spec.ts
- projects/ngx-datatable/src/lib/utils/column-prop-getters.ts
- projects/ngx-datatable/src/lib/utils/throttle.ts
- src/app/basic/filter.component.ts
- src/app/basic/row-grouping.component.ts
Following rules are enabled:
- '@typescript-eslint/no-this-alias'
- '@typescript-eslint/dot-notation'
- '@typescript-eslint/prefer-includes'
- prefer-rest-params
> refactor: enable lint rules

- eslint.config.mjs
- src/app/basic/contextmenu.component.ts
- src/app/basic/dynamic-height.component.ts
- src/app/basic/inline.component.ts
- src/app/basic/responsive.component.ts
- src/app/basic/row-detail.component.ts
- src/app/basic/row-grouping.component.ts
- src/app/basic/scrolling-dynamically.component.ts
- src/app/basic/virtual.component.ts
- src/app/selection/selection-cell.component.ts
- src/app/selection/selection-chkbox-template.component.ts
- src/app/selection/selection-chkbox.component.ts
- src/app/selection/selection-disabled.component.ts
- src/app/selection/selection-multi-click-chkbox.component.ts
- src/app/selection/selection-multi-click.component.ts
- src/app/selection/selection-multi.component.ts
- src/app/selection/selection-single.component.ts
- src/app/sorting/sorting-comparator.component.ts
- src/app/sorting/sorting-server.component.ts
> refactor: enable no-console rule

- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.html
- [] Refactoring (no functional changes, no api changes)
> fix: avoid duplicate row identity warnings

- eslint.config.mjs
- src/app/paging/paging-scrolling-novirtualization.component.ts
- src/app/paging/paging-server.component.ts
- src/app/paging/paging-virtual.component.ts
- src/app/paging/scrolling-server.component.ts
- src/app/summary/summary-row-server-paging.component.ts
- src/app/tree/fullscreen.component.ts
> refactor: enable prefer-inject

- eslint.config.mjs
- src/app/selection/selection-chkbox-template.component.ts
- src/app/selection/selection-chkbox.component.ts
- src/app/selection/selection-disabled.component.ts
- src/app/selection/selection-multi-click-chkbox.component.ts
- src/app/selection/selection-multi-click.component.ts
- src/app/selection/selection-multi.component.ts
- src/app/selection/selection-single.component.ts
> refactor: enable prefer-at-empty

- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
Row class calculation uses string concatenation.
Row class calculation uses string concatenation, but less.
And binding is now done in host field which prepares signal migration.
There will be more of this kind coming up.
> refactor: simplify row class calculation

- projects/ngx-datatable/src/lib/directives/visibility.directive.ts
`VisibilityDirective` uses @Input and @Output
`VisibilityDirective` uses input and output signals
Maybe it's possible to migrate the visibility directive into an `afterNextRender` effect.
> refactor: migrate visibility directive to signals

- projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
`DatatableRowDetailDirective` uses @Input and @Output
`DatatableRowDetailDirective` uses input and output signals
> refactor: migrate row-detail directive to signals

- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
- projects/ngx-datatable/src/lib/components/body/summary/testing/summary.harness.ts
This PR does following changes:
- protected internals
- updated unit tests and added test harness
- migrated to signal inputs and computed
> refactor: summary row

- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.html
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.ts
> refactor(ghost-loaders): migrate to signals

- projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
- projects/ngx-datatable/src/lib/components/body/body-row.component.ts
- projects/ngx-datatable/src/lib/components/body/body.component.ts
- projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
- projects/ngx-datatable/src/lib/components/datatable.component.html
- projects/ngx-datatable/src/lib/ngx-datatable.config.ts
> feat: support custom classes for tree toggle icons

- projects/ngx-datatable/src/lib/components/footer/pager.component.spec.ts
- projects/ngx-datatable/src/lib/components/footer/pager.component.ts
- projects/ngx-datatable/src/lib/components/footer/testing/pager.harness.ts
> fix(pagination): allow space/enter event to paginate

- projects/ngx-datatable/src/lib/components/body/body-cell.component.spec.ts
- projects/ngx-datatable/src/lib/components/body/testing/body-cell.harness.ts
> test(body-cell): add unit tests
